# update IPs after terraform apply, or pull from `terraform output vm_default_ip`

[webservers]
web-01 ansible_host=192.168.1.100 ansible_user=packer ansible_ssh_private_key_file=~/.ssh/rscc_id_rsa
web-02 ansible_host=192.168.1.101 ansible_user=packer ansible_ssh_private_key_file=~/.ssh/rscc_id_rsa

[dbservers]
db-01  ansible_host=192.168.1.102 ansible_user=packer ansible_ssh_private_key_file=~/.ssh/rscc_id_rsa

[all_vms:children]
webservers
dbservers

[all_vms:vars]
ansible_python_interpreter=/usr/bin/python3
